### PR TITLE
Fix CDN convert using URI.js

### PR DESCRIPTION
**Pull request by maxep**
# Provide a more robust URI conversion when using CDN.

For some mime (like audio) the `Location` format differs, and so the URL conversion using `data.Location.replace` fails.
By using [URI.js](https://medialize.github.io/URI.js/), we can easily enforce the URL to the following format:
`https//<config.cdn>/<object.key>`

### CODE REVIEW

**Comment by pturner1989** [comment]
@maxep Thank you, this issue was driving me mad. Currently using #5 in my project.

**Comment by amantiwari1** [comment]
hey, @pturner1989 there is no mention about set private or public optional!! -  I mean how do I do that? is it even possible?

**Comment by shorwood** [comment]
Just checked that out and it's a great contribution ! Sorry for the delay, better late than never, i'll merge in. ;)

**Comment by amantiwari1** [comment]
@shorwood  help!, there is no mention about set private or public optional!! - I mean how do I do that? is it even possible?

**Comment by maxep** [comment]
@amantiwari1 currently no. Uploads are `public-read`, see [index.js#L65](https://github.com/shorwood/strapi-provider-upload-do/blob/master/lib/index.js#L65). That's the same behavior as the [official aws-s3 strapi plugin](https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-aws-s3/lib/index.js#L28).

**Pull request merged**
