### PR TITLE
Add missing upload stream function

### PR DESCRIPTION
**Pull request by duxor**
Function `uploadStream` is required in the strapi v4 (ex. logo upload)

### CODE REVIEW

**Comment by m90khan** [comment]
Sorry for writing here but the video previews are not working in admin panel because video URL does not have https:// in front of it.
I just tried with your plugin as well. below is the complete thread. 
Can you please provide any help in this case?
https://forum.strapi.io/t/video-preview-not-working-when-using-strapi-with-digitalocean-spaces/21716

**Comment by FabianClemenz** [comment]
Is this needed to get this plugin to work with strapi 4.3.6 for media uploads?

**Comment by m90khan** [comment]
Thanks for your response. I am using the latest version of strapi.

 Yes, this is very crucial to view the video preview besides it also strips out https:// which does have issues on the API response on the client side, especially when doing static site generation.
 
 I have tested most of the plugins including those ones that forked your project but have the same issue.

**Comment by prionkor** [comment]
Need merge this PR. Getting the following warning...

```
Warning: The upload provider "strapi-provider-upload-do" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by shorwood** [comment]
Hi, Thanks for the contribution,

I just reviewed it and it was indeed missing for a long time.

I'm sorry I couldn't review it sooner.

Package is now available on [npm](https://www.npmjs.com/package/strapi-provider-upload-do/v/3.6.7)

**Pull request merged**
